### ISSUE TITLE
npm start

### ISSUE THREAD

**Issue by danilocecilia** [jcloutz/fcc-tic-tac-toe#1]
Hello, could you provide some instruction on how to run this project on local machine?

I did npm install and npm start and didn't work.

`npm start

> fcc-tic-tac-toe@2.0.0 start C:\Users\Danilo\Downloads\fcc-tic-tac-toe-master\fcc-tic-tac-toe-master
> hjs-dev-server

events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND kragle.local
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
Emitted 'error' event at:
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1457:12)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fcc-tic-tac-toe@2.0.0 start: `hjs-dev-server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fcc-tic-tac-toe@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Danilo\AppData\Roaming\npm-cache\_logs\2019-04-09T02_14_29_420Z-debug.log`

**Comment by jcloutz** [comment]
Hello @danilocecilia,

The issue is the hostname configured in webpack.config.js. You should be able to change it from `kragle.local` to `localhost` to run it.

**Comment by danilocecilia** [comment]
That's it! Thank you!
